### ISSUE TITLE
colorCoding setting is failing in Logback and doesn't get picked up

### ISSUE THREAD

**Issue by jmorelandsbiz** [maricn/logback-slack-appender#15]
Following the example given, everything works but I get an error on colorCoding in Logback's setup: 
-ERROR in ch.qos.logback.core.joran.spi.Interpreter@46:18 - no applicable action for [colorCoding], current ElementPath  is [[configuration][appender][colorCoding]]

This makes colorCoding stay set to false and I don't get that red color for errors.

**Comment by jmorelandsbiz** [comment]
Ok. It looks like 1.3 doesn't have this feature yet. Any way that this can get pushed?

**Comment by maricn** [comment]
@jmorelandsbiz Released version 1.4.0.
