### ISSUE TITLE
Release a new version due to Jackson update

### ISSUE THREAD

**Issue by robertoschwald** [maricn/logback-slack-appender#26]
Dependabot upgraded the jackson-databind version several times in this project due to high / critical CVE issues in de-serialization.
Even when this appender does not use the unmarshaller methods scoped by the CVEs, it might be possible that applications using this appender will automatically pick up Jackson for marshalling.
Therefore I think it is a good idea to release a new version of the appender with the upgraded Jackson dependencies.

**Comment by maricn** [comment]
Sorry for the delay. 1.6.0 release is published now
