### ISSUE TITLE
License

### ISSUE THREAD

**Issue by kiru** [maricn/logback-slack-appender#3]
Hello @maricn, 

Thank you for this repository. 

What is the license of this repository? I'd like to you the SlackAppender class ( only that class ). 

Could you specify a license?

Thank you, 
Kiru

**Comment by maricn** [comment]
Hi @kiru,

There is a license file at root of the repository https://github.com/maricn/logback-slack-appender/blob/master/LICENSE. You may reuse that class as you wish. [More info about Apache 2.0](https://www.whitesourcesoftware.com/whitesource-blog/top-10-apache-license-questions-answered/).

Best,
Nikola
