### ISSUE TITLE
Support Slack's Incoming WebHooks

### ISSUE THREAD

**Issue by lhanson** [maricn/logback-slack-appender#5]
Slack allows easy integration via webhooks, it would be convenient if `logback-slack-appender` could be configured by simply providing a webhook URL rather than generating tokens and providing explicit username and channel configuration.

[https://api.slack.com/incoming-webhooks](https://api.slack.com/incoming-webhooks)

**Comment by niqdev** [comment]
Hi @maricn , is the latest version with the webhook released on maven?
At the moment is version [1.2.0](https://mvnrepository.com/artifact/com.github.maricn/logback-slack-appender/1.2.0)
Thanks
